# 45장. 프로미스

- 자바스크립트는 비동기 처리를 위해 콜백 함수 사용
  - 콜백 헬에 빠질 수 있음
  - 에러 처리 곤란
- 비동기 처리를 위한 또 다른 방법으로 ES6에서 프로미스 도입

<br/>
<br/>

## ✅ 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1 콜백 헬

- 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.
  - 비동기 함수 내부의 비동기로 동작하는 코드의 처리 결과를 내부로 반환하는 것이 불가하다.
  - 상위 스코프의 변수에 할당이 불가하다.
- setTimeout 함수가 비동기 함수인 이유
  - 콜백 함수의 호출이 비동기로 동작하기 때문이다.
  - setTimeout 함수를 호출하면 콜백 함수를 호출 스케쥴링 한 후, 타이머 id를 반환하고 즉시 종료된다.

```jsx
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  // onload 이벤트 핸들러 (비동기 동작 -> get 함수는 비동기 함수이다.)
  xhr.onload = () => {
    if (xhr.status === 200) {
      return JSON.parse(xhr.response);
    }
    console.error(`${xhr.status} ${xhr.statusText}`);
  };
};

const response = get("https://jsonplaceholder.typicode.com/posts/1");
console.log(response); // undefined
```

- 위의 코드에서 get 함수 내부의 onload 이벤트 핸들러는 get 함수가 종료된 이후에 실행된다.
- 비동기 함수의 처리 결과(서버의 응답 등)에 대한 후속 처리는 반드시 비동기 함수 내부에서 수행해야 한다.
  - 일반적으로 비동기 처리 결과에 대한 후속 처리를 수행하기 위해 비동기 함수에 콜백 함수를 전달한다. (아래 코드와 같다.)

```jsx
// 비동기 함수의 인자로 비동기 함수의 처리 결과에 대한 후속처리를 위한 콜백 함수를 전달한다.
const get = (url, successCallback, failureCallback) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      successCallback(JSON.parse(xhr.response));
    } else {
      failureCallback(xhr.status);
    }
  };
};

get("https://jsonplaceholder.typicode.com/posts/1", console.log, console.error);
```

- 콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또 다시 비동기 함수를 호출해야 할 경우 콜백 함수 호출이 중첩되고, 복잡도가 높아지게 된다.
  - 이것이 바로 콜백 헬 (아래 코드의 예시와 같다.)

```jsx
get(`${url}/posts/1`, ({ userId }) => {
  console.log(userId);
  get(`${url}/users/${userId}`, (userInfo) => {
    console.log(userInfo);
  });
});
```

<br/>

### 45.1.2 에러 처리의 한계

- 비동기 처리를 위한 콜백 패턴의 또 다른 문제는 에러 처리가 곤란하다는 것이다.

```jsx
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다.
  console.error("캐치한 에러", e);
}
```

- setTimeout의 콜백 함수가 실행될 때 setTimeout 함수는 이미 콜 스택에서 제거된 상태다
  - 이것은 콜백 함수를 호출한 것이 setTimeout 함수가 아니라는 것을 의미한다.
  - 따라서, setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.

<br/>
<br/>

## ✅ 45.2 프로미스의 생성

- Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스(promise 객체)를 생성한다.
- Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수(resolve, reject 함수를 인수로 전달 받음)를 인수로 전달 받는다.

```jsx
const promise = new Promise((resolve, reject) => {
    if (/* 비동기 처리 성공 */) {
        resolve('result');
    } else { /* 비동기 처리 실패 */
        reject('failure reason')
    }
});
```

- Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행한다.
  - 비동기 처리 성공 시 : 콜백 함수의 인수로 전달 받은 resolve 함수 호출
  - 비동기 처리 실패 시 : 콜백 함수의 인수로 전달 받은 reject 함수 호출
- 프로미스는 현재 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보를 가진다.
  - pending : 비동기 처리가 아직 수행되지 않은 상태
  - settled : 비동기 처리가 수행된 상태
    - fulfilled : 비동기 처리가 성공
    - rejected : 비동기 처리가 실패
- 프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체이다.

<br/>
<br/>

## ✅ 45.3 프로미스의 후속 처리 메서드

- 프로미스의 비동기 처리 상태가 변화하면 후속 처리를 해야한다.
- 프로미스의 후속 처리 메서드
  - then, catch, finally
  - 프로미스의 비동기 처리 상태가 변화하면, 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.

### 45.3.1 Promise.prototype.then

- then 메서드는 두 개의 콜백 함수를 인수로 전달 받는다.
  - 첫 번째 콜백 함수 : 프로미스가 resolve 함수가 호출된 상태가 되면 호출한다. 프로미스의 비동기 처리 결과를 인수로 전달 받는다.
  - 두 번째 콜백 함수 : 프로미스가 reject 함수가 호출된 상태가 되면 호출한다. 프로미스의 에러를 인수로 전달 받는다.

```jsx
// fulfilled
new Promise((resolve) => resolve("fulfilled")).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // fulfilled
// rejected
new Promise((_, reject) => reject(new Error("rejected"))).then(
  (v) => console.log(v),
  (e) => console.err(e)
); // Error: rejected
```

- 이 때, then 메서드는 언제나 프로미스를 반환한다.

### 45.3.2 Promise.prototype.catch

- catch 메서드는 한 개의 콜백 함수를 인수로 전달 받는다.
- 프로미스가 rejected 상태인 경우만 호출된다.
- then(undefined, onRejected) 와 동일하게 동작한다.

### 45.3.3 Promise.prototype.finally

- finally 메서드는 한 개의 콜백 함수를 인수로 전달 받는다.
- 프로미스의 성공과 실패와 상관 없이 무조건 한 번 호출된다.

```jsx
// 프로미스로 구현한 비동기 함수 get을 사용해 후속처리 해보기
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달 받으면 resolve 함수 호출
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출
        reject(new Error(xhr.status));
      }
    };
  });
};

promiseGet("https://jsonplaceholder.typicode.com/posts/1")
  .then((res) => console.log(res))
  .catch((err) => console.error(err))
  .finally(() => console.log("Bye!"));
```

<br/>
<br/>

## ✅ 45.4 프로미스의 에러 처리

- 비동기 처리를 위한 콜백 패턴은 에러 처리가 곤란하지만,
- 프로미스는 에러를 문제없이 처리할 수 있다. 두 가지 방법이 존재한다.
  - then 메서드의 두 번째 콜백 함수를 활용한다.
    - then 메서드의 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고, 코드가 복잡해서 가독성이 좋지 않다.
  - (권장) catch 메서드를 활용한다.

```jsx
// then 메서드를 활용하여 에러를 처리할 때의 문제점
promiseGet("https://jsonplaceholder.typicode.com/todos/1").then(
  (res) => console.xxx(res),
  (err) => console.log(err) // 두 번째 콜백 함수는 첫 번째 콜백 함수의 에러를 감지하지 못한다.
);
// catch 메서드를 활용하여 에러 처리
promiseGet("https://jsonplaceholder.typicode.com/todos/1")
  .then((res) => console.xxx(res))
  .catch((err) => console.error(err)); // TypeError : console.xxx is not a function
```

<br/>
<br/>

## ✅ 45.5 프로미스 체이닝

- 비동기 처리를 위한 콜백 패턴은 콜백 헬이 발생하는 문제가 있지만,
- 프로미스는 then, catch, finally 메서드를 통해 콜백 헬을 해결한다.
- 프로미스의 후속 처리 메서드는 언제나 프로미스를 반환하므로, 연속적으로 호출할 수 있다.

```jsx
const url = "https://jsonplaceholder.typicode.com";

// id가 1인 post의 userId 취득
promiseGet(`${url}/posts/1`)
  // 취득한 post의 userId로 user 정보를 취득
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then((userInfo) => console.log(userInfo))
  .catch((err) => console.error(err));
```

<br/>
<br/>

## ✅ 45.6 프로미스의 정적 메서드

### 45.6.1 Promise.resolve / Promise.reject

- 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.

```jsx
// 배열을 resolve 하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1,2,3]
// 아래와 동일하게 동작한다.
const resolvedPromise = new Promise((resolve) => resolve([1, 2, 3]));
resolvedPromise.then(console.log); // [1,2,3]

// 에러 객체를 reject 하는 프로미스를 생성
const rejectedPromise = Promise.reject(new Error("Error!"));
rejectedPromise.catch(console.log); // Error : Error!
```

### 45.6.2 Promise.all

- Promise.all 메서드는 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다.
  - 여러 개의 비동기 처리가 서로 의존하지 않고 개별적으로 수행할 때 활용된다.
- Promise.all 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받는다.
- Promise.all 메서드는 인수로 전달 받은 배열의 모든 프로미스가 모두 fulfilled 상태가 되면 종료한다.
  - 모든 프로미스가 fulfilled 상태가 되면 resolve된 처리 결과 모두를 배열에 저장하여, 새로운 프로미스를 반환한다.
- 처리 순서가 보장된다.
  - 예를 들어, 첫 번째 프로미스가 가장 나중에 fulfilled 상태가 되어도, 첫 번째 프로미스가 resolve한 처리 결과부터 차례대로 배열에 저장한다.
- 만약 인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 즉시 종료한다.

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 병렬로 처리
Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [1,2,3] -> 약 3초 소요
  .catch(console.error);
```

- 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용하는 Promise.all 메서드의 활용 예시이다.

```jsx
// Promise.all 메서드를 사용해서 깃 허브 아이디로 사용자 이름 취득하기
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        resolve(JSON.parse(xhr.response));
      } else {
        reject(new Error(xhr.status));
      }
    };
  });
};

const gitHubId = ["jeresig", "ahejlsberg", "ungmo2"];

Promise.all(
  githubId.map((id) => promiseGet(`https://api.github.com/users/${id}`))
)
  .then((users) => users.map(users.map((user) => user.name)))
  .then(console.log)
  .catch(console.error);
```

### 45.6.3 Promise.race

- Promise.race 메서드는 Promise.all 메서드와 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받는다.
- Promise.race 메서드는 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 프로미스를 반환한다.
- 프로미스가 rejected 상태가 되면 에러를 reject 하는 새로운 프로미스를 즉시 반환한다.

### 45.6.4 Promise.allSettled

- Promise.allSettled 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다.
- Promise.allSettled 메서드는 fulfilled, rejected 상태와는 상관 없이 모든 프로미스들의 처리 결과가 담긴 배열을 반환한다.

<br/>
<br/>

## ✅ 45.7 마이크로태스크 큐

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
// 2 -> 3 -> 1 순서로 출력
```

- 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아닌 마이크로태스크 큐에 저장된다.
  - 마이크로태스크 큐는 태스크 큐보다 우선 순위가 높다.

<br/>
<br/>

## ✅ 45.8 fetch

- fetch 함수 : HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API
- fetch 함수에는 HTTP 요청을 전송할 URL, HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.
- fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.

```jsx
fetch("https://jsonplaceholder.typicode.com/todos/1").then((response) =>
  console.log(response)
);
```

- fetch 함수가 반환한 프로미스가 래핑하고 있는 MIME 타입이 application/json인 HTTP 응답 몸체를 취득하려면 Response.prototype.json 메서드를 사용해야 한다.
  - Response.prototype.json 메서드 : Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.

```jsx
fetch("https://jsonplaceholder.typicode.com/todos/1")
  // json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화
  .then((response) => response.json())
  .then((json) => console.log(json));
```

- fetch 함수는 404 에러와 같은 HTTP 에러가 발생해도 에러를 reject하지 않고,
  - 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve한다.
- fetch 함수는 오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject 한다.
- 따라서, fetch 함수를 사용할 때는, fetch 함수가 반환한 프로미스가 resolve한 불리언 타입의 ok 상태를 확인해 에러를 처리해야 한다.

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/xxx/1";

// 부적절한 URL로 인해 404 에러 발생
fetch(wrongUrl)
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText);
    return reponse.json();
  })
  .then((todo) => console.log(todo))
  .catch((err) => console.error(err));
```

- fetch 함수를 통해 HTTP 요청 전송하기
  - 첫 번째 인수 : HTTP 요청을 전송할 URL
  - 두 번째 인수 : 객체 (HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등)
