# 46장. 제너레이터와 async/await

## ✅ 46.1 제너레이터란?

- ES6에서 도입된 제너레이터는 코드 블록의 실행을 일시 중지했다가, 필요한 시점에 재개할 수 있는 특수한 함수다.
  - 제너레이터는 함수 호출자가 함수 실행을 일시 중지시키거나 재개할 수 있다.
  - 제너레이터는 함수 호출자에게 상태를 전달할 수 있고 함수 호출자로부터 상태를 전달받을 수도 있다.
  - 제너레이터 함수를 호출하면 함수 코드를 실행하는 것이 아니라 제너레이터 객체를 반환한다.
- function\* 키워드로 선언
- 하나 이상의 yield 표현식을 포함한다.
- 화살표 함수로 정의할 수 없다.
- new 연산자와 함께 생성자 함수로 호출할 수 없다.

<br/>
<br/>

## ✅ 46.3 제너레이터 객체

- 제너레이터 함수를 호출하면 일반 함수처럼 함수 코드 블록을 호출하는 것이 아니라 제너레이터 객체를 생성한다.
  - 제너레이터 객체는 이터러블이면서 동시에 이터레이터다.
  - Symbol.iterator 메서드를 상속받는 이터러블이다.
  - value, done 프로퍼티를 갖는 이터레이터 리절트 객체를 반환하는 next 메서드를 소유하는 이터레이터이다.
- 제너레이터 객체는 next 메서드를 갖는 뿐만 아니라 return, throw 메서드를 갖는다.
- next 메서드를 호출하면 yield 표현식까지 코드 블록을 실행하고, yield된 값을 value 프로퍼티 값으로, false를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.
- return 메서드를 호출하면 인수로 전달받은 값을 value 프로퍼티 값으로, true를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.

```jsx
function* genFunc() {
  try {
    yield 1;
    yield 2;
    yield 3;
  } catch (e) {
    console.error(e);
  }
}

const generator = genFunc();

console.log(generator.next()); // {value: 1, done: false}
console.log(generator.return("End!")); // {value: 'End!', done: true}
console.log(generator.throw("Error!")); // {value: undefined, done: true}
```

<br/>
<br/>

## ✅ 46.4 제너레이터의 일시 중지와 재개

- 제너레이터는 yield 키워드와 next 메서드를 통해 실행을 일시 중지했다가 필요한 시점에 다시 재개할 수 있다.
- 제너레이터 객체의 next 메서드를 호출하면 yield 표현식까지만 실행한다.
- 이 때, 함수의 제어권이 호출자로 양도된다.
- 호출자가 또 다시 next 메서드를 호출하면 일시 중지된 코드부터 실행을 재개하여 다음 yield 표현식까지 실행되고 또 다시 일시 중지된다.

<br/>
<br/>

## ✅ 46.6 async/await

- async/await는 프로미스 기반으로 동작한다.
- 동기 처리처럼 프로미스를 사용할 수 있다.
  - 프로미스의 후속 처리 메서드 없이 프로미스가 처리 결과를 반환하도록 구현할 수 있다.

```jsx
const fetch = require("node-fetch");

async function fetchTodo() {
  const url = "https://url";

  const response = await fetch(url);
  const todo = await response.json();
  console.log(todo);
  // {userId: 1, id: 1, title: 'hello', completed: false}
}
```

### 46.6.1 async 함수

- async 함수는 언제느 프로미스를 반환한다.

```jsx
async function foo(n) {
  return n;
}
foo(1).then((v) => console.log(v)); // 1

const bar = async function (n) {
  return n;
};
bar(2).then((v) => console.log(v)); // 2

const baz = async (n) => n;
baz(3).then((v) => console.log(v));

const obj = {
  async foo(n) {
    return n;
  },
};
obj.foo(4).then((v) => console.log(v)); // 4

class MyClass {
  async bar(n) {
    return n;
  }
}
const myClass = new Myclass();
myClass.bar(5).then((v) => console.log(v)); // 5
```

<br/>

### 46.6.2 await 키워드

- await 키워드는 반드시 프로미스 앞에서 사용한다.
- await 키워드는 프로미스가 settled 상태가 될 때까지 대기하다가, settled 상태가 되면 프로미스가 resolve한 처리 결과를 반환한다.
  - 즉, await 키워드는 다음 실행을 일시 중지시켰다가 프로미스가 settled 상태가 되면 다시 재개한다.
- 비동기 처리의 처리 순서가 보장될 때는 await 키워드를 써서 순차적으로 처리한다.
  - 반면, 비동기 처리가 서로 연관이 없는 경우 Promise.all() 을 활용한다

```jsx
async function foo() {
  const res = await Promise.all([
    new Promise((resolve) => setTimeOut(() => resolve(1), 3000)),
    new Promise((resolve) => setTimeOut(() => resolve(2), 2000)),
    new Promise((resolve) => setTimeOut(() => resolve(3), 1000)),
  ]);

  console.log(res); // [1, 2, 3];
}

foo(); // 약 3초 소요
```

<br/>

### 46.6.3 에러 처리

- async/await에서 에러 처리는 비동기 처리를 위한 콜백 패턴과는 다르게 try...catch 문을 사용할 수 있다.
- 이 때, catch문은 HTTP 통신에서 발생한 네트워크 에러뿐 아니라, try 코드 블록 내의 모든 문에서 발생한 일반적인 에러까지 캐치할 수 있다.

```jsx
const fetch = require("node-fetch");

const foo = async () => {
  try {
    const wrongUrl = "https://wrong";

    const response = await fetch(wrongUrl);
    const data = await response.json();
    console.log(data);
  } catch (err) {
    console.log(err);
  }
};
```
