# 47장. 에러처리

## ✅ 47.1 에러 처리의 필요성

- 발생한 에러를 대처하지 않고 방지하면 프로그램은 강제 종료된다.

```jsx
console.log("start");
foo(); // ReferenceError
// 프로그램 강제 종료

console.log("end"); // 에러에 의해 프로그램이 강제 종료되어 실행되지 않는다.
```

- try ... catch 구문을 사용하여 에러가 발생해도 프로그램이 강제 종료되지 않도록 할 수 있다.

```jsx
console.log("start");

try {
  foo();
} catch (e) {
  console.error("에러 발생", e);
  // 에러 발생 ReferenceError
}

// 발생한 에러에 대해 대응했으므로 프로그램이 강제 종료되지 않고 아래 구문이 실행된다.
console.log("end");
```

<br/>
<br/>

## ✅ 47.2 try...catch...finally문

- 에러를 처리하는 두 가지 방법
  1. 반환하는 값을 if문, 단축 평가, 옵셔널 체이닝 연산자를 통해 확인하여 처리하는 방법
  2. try...catch...finally 문을 통해 에러 처리 코드를 미리 등록해두고 에러가 발생하면 에러 처리 코드로 점프하는 방법

```jsx
try {
  // 실행할 코드 (에러가 발생할 확률이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러 발생 시 이 코드 블록의 코드가 실행
  // err 에는 try 코드 블록에서 발생한 Error 객체가 전달
} finally {
  // 무조건 한 번 실행
}
```

<br/>
<br/>

## ✅ 47.3 Error 객체

- Error 생성자 함수는 에러 객체를 생성한다.
  - Error 생성자 함수에는 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있다.

```jsx
const error = new Error("invalid.. 에러 메시지를 인수로 전달 가능");
```

- Error 생성자 함수가 생성한 에러 객체는 message 프로퍼티와 stack 프로퍼티를 가진다.
  - message 프로퍼티 : Error 생성자 함수에 인수로 전달한 에러 메시지
  - stack 프로퍼티 : 에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열. 디버깅 목적
- Error 생성자 함수
  - Error : 일반적 에러 객체
  - SyntaxError : 자바스크립트 문법 에러
  - RefereneError : 참조할 수 없는 식별자 에러
  - TypeError : 피연산자, 인수의 데이터 타입 에러
  - RangeError : 숫자의 허용 범위 초과 에러
  - URIError : encodeURI, decodeURI에 부적절한 인수 에러
  - EvalError : eval 함수에서 발생하는 에러

<br/>
<br/>

## ✅ 47.4 throw문

- 에러 객체를 생성하고 에러 발생은 따로 시켜줘야 한다.

```jsx
try {
    // 에러 객체를 생성한다고 에러가 발생하는 것은 아니다.
    // 에러 객체를 던져야지 catch 코드 블록이 실행되기 시작한다.
    new throw Error('something wrong');
} catch (error) {
    console.log(error);
}
```

<br/>
<br/>

## ✅ 47.5 에러의 전파

- throw된 에러를 캐치하지 않으면 에러는 호출자 방향으로 계속 전파된다.
  - 전역까지 전파될 수 있음
  - 따라서, throw된 에러를 캐치하여 적절히 대응해야 함
- 비동기 함수인 setTimeOut이나 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없다. 즉, 에러를 전파할 호출자가 없다.
